apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feedback-fusion.fullname" . }}
  labels:
    {{- include "feedback-fusion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "feedback-fusion.selectorLabels" . | nindent 6 }}
      onelitefeather.net/feedback-fusion-component: server
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "feedback-fusion.labels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "feedback-fusion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 8000 
              protocol: TCP
          env:
            - name: RUST_LOG 
              value: {{ .Values.feedbackFusion.log }}
            - name: FEEDBACK_FUSION_CONFIG
              value: /etc/config/config.hcl
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.server.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

            - name: {{ .Values.feedbackFusion.config.secret }}
              mountPath: /etc/config
      volumes:
        {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        - name: {{ .Values.feedbackFusion.config.secret }}
          secret:
            secretName: {{ .Values.feedbackFusion.config.secret }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
